version: '3.4'

services:
 
  microservice1:
    container_name: listings
    image: ${DOCKER_REGISTRY-}microservice1
    build:
      context: .
      dockerfile: Microservice1\Dockerfile
    ports: 
      - 8001:80
  


